### ISSUE TITLE
Right SideNav doesn't work

### ISSUE THREAD

**Issue by mkzaker** [Dogfalo/materialize#1488]
Hi,
I need sideNav on right side of screen. i try with this:

class="side-nav **fixed** right-aligned"

its work but after this:

$(".button-collapse").sideNav({ edge: 'right' });

it get "right: -250px; left: 0px;" attributes

**Comment by thomaslarsson** [comment]
Try 'right' instead of 'right-aligned'. Not a bug.

**Comment by FerdinandvHagen** [comment]
unfortunately I have the same problem. Environment: Opera 29.0 and materializecss 0.96.1 via bower. My sidenav in html:
<ul id="slide-out" class="side-nav fixed right">
    etc...
</ul>

Tested as well without "right" and with "right-align" etc... It's always the same problem. The sideNav sticks to the left side until I resize the window forcing it to go to tablet mode and hiding and then redisplaying the sideNav. Then everything is correct and it is on the right side.

The devtools in my browser show the following difference:
"right-align" class is automatically added (seems legit)
if I just load the page a style tag is added: style="right: -250px; left: 0px;"
after resizing the page (as explained forcing it into tablet mode) style looks like this: style="width: 240px;" which works perfectly fine.

Am I just doing it wrong or is it indeed a bug?

JavaScript looks like this (thats all just some empty AngularJS controller in the background):
$('.button-collapse').sideNav({
    edge: 'right', // Choose the horizontal origin
    menuWidth: 240
  }
);

$(document).ready(function(){
  $('ul.tabs').tabs();
});

**Comment by FerdinandvHagen** [comment]
Just added a quick workaround. It's very hacky and the sideNav jumps from the left to the right edge after page load but it works:

```js
var menu_id = $("#"+ $('.button-collapse').attr('data-activates'));
menu_id.css('width', '240px');
menu_id.css('right', '');
menu_id.css('left', '');
```

**Comment by iSuslov** [comment]
Guys, I may be wrong, but I think this is already fixed in master. A month ago maybe, I downloaded materialize from their official site, and after found out this bug, fixed it and tried to make pull request. But when I cloned master branch, I've found out that it has this fix already.

**Comment by FerdinandvHagen** [comment]
Still couldn't get it working. I created a pull request with a solution that is working for me.

**Comment by Dogfalo** [comment]
This issue has been tested and is fixed.

**Comment by renefs87** [comment]
I think it is not fixed. It stills happening to me...

**Comment by Dogfalo** [comment]
I think it is related to angular calling the function many times

**Comment by zionnite** [comment]
i don't think this issue is fixed....
you said something @FerdinandvHagen, but for me when i re-sized my page the side nav button disapper on device and user cant navigate on the site but when i used google chrome to inspect my element i found addition parameter which was "left:-250px

**Comment by eresik** [comment]
Really not fixed!

**Comment by arahmanali** [comment]
Still facing this issue, any update?

**Comment by brojask** [comment]
Hi! I had the same problem. I found the way to solve it but is still a issue. 
Please check this out: http://codepen.io/bryanrojas/pen/YydLPO

**Comment by frankros91** [comment]
Can confirm this is not fixed.  It's hacky but this is how I solved it.  
$collapseButton.sideNav({edge: 'right'});
//granb the ul
var menu = React.findDOMNode(this.refs.notificationCenter);
var $menu = window.$(menu);
$menu.removeAttr('style');

**Comment by nicolefinnie** [comment]
We hit the same problem too
1) side-nav doesn't swap to right, when data-sidenav = "right" is called, until the window gets resized
2) but it swaps to the left as soon as the condition is met.  when data-sidenav = "left" is called
3) We're still in 0.97.2 due to the grid bugs in 0.97.3 - 0.97.5, it seems this issue hasn't been fixed in the latest version 0.97.5 either, so we don't bother to move up until both issues are fixed.

**Comment by gg4u** [comment]
hello and hi @brojask , I've seen indeed your version is working. Could you please share the patch you did from lines 2006 to 2015 ? `$(function() {

  $("[data-activates=slide-out-l]").sideNav();
  $("[data-activates=custom-menu]").sideNav({
    edge: 'right'
  });
})` 

worked only once, at second click it will pop of from left again. I also noticed that grey background will be layered after multiple openings, a similar issue to modals background layer.

**Comment by brojask** [comment]
Hi Luigi! For a fast solution you could check this CodePen that I share for
this bug. Actually I didn't  patch anything form the source code but I
think it could be better.

I hope this can help you: http://codepen.io/bryanrojas/pen/YydLPO

Greetings, Bryan R.

2016-01-03 8:14 GMT-06:00 Luigi <notifications@github.com>:

**Comment by gg4u** [comment]
thank you @brojask , I indeed updated my reply. Thank you very much for sharing!

**Comment by DantewithZYX** [comment]
@iSuslov Your commit reference worked for me v0.97.5. Thanks!

**Comment by beshambher** [comment]
Same issue here.

**Comment by leolr02** [comment]
The temporary solution is override the css props when the page already loaded
example:
$(function () {
var rightSideNav = $(".button-collapse").attr("data-target");
// Delay 200 ms
setTimeout(function () {
  $("#"+rightSideNav).attr("style", "");
}, 200);
});

**Comment by Dogfalo** [comment]
Fixed in v1-dev
