### ISSUE TITLE
Search icon in nav, incorrect alignment

### ISSUE THREAD

**Issue by vinaybedre** [Dogfalo/materialize#1796]
![parallax_template_-_materialize](https://cloud.githubusercontent.com/assets/2630384/8888567/17244eaa-32d0-11e5-917a-175f88b3225e.png)
Search icon in navbar has incorrect alignment. see screenshot above. This can also be viewed at http://materializecss.com/navbar.html

**Comment by carlosperate** [comment]
Which browser are you using? could you specify which example from http://materializecss.com/navbar.html displays the same alignment issue? I'm looking at it right now and cannot really spot it.

It would be a lot easier to help you out if you could provide a codepen illustrating your problem, as indicated in the [contributing](https://github.com/Dogfalo/materialize/blob/master/CONTRIBUTING.md) file.

**Comment by acburst** [comment]
Is it the issue I fixed in 43d43c27960ba7fd6eff16b4daadcd7e2dba6294?

**Comment by vinaybedre** [comment]
Hi,

I'm using Google chrome on nexus 5, lollypop.
In above page, search section has this issue.

Regards,
Vinay

**Comment by carlosperate** [comment]
Have you been able to try the Materialize source files from https://github.com/Dogfalo/materialize/tree/master/bin ?
The commit that acburst has linked to (https://github.com/Dogfalo/materialize/commit/43d43c27960ba7fd6eff16b4daadcd7e2dba6294) has been added after 0.97.0 was release, so it would only be fixed in the versions from the master branch in this repository.

**Comment by carlosperate** [comment]
Just to confirm that I have tried master@https://github.com/Dogfalo/materialize/commit/76daf9590a160235bd2005fc3e3f27866245795c and the issue persist in lollipop.

**Comment by Josepdal** [comment]
I have the same problem

**Comment by tomscholz** [comment]
Can anybody confirm that this issue still persist?
Anyhow I am going to close this issue for now.
