### ISSUE TITLE
<select multiple> broken

### ISSUE THREAD

**Issue by MeMyselfI** [Dogfalo/materialize#2274]
Hi.

Well, where to start... 
1. I think it doesn't handle < option selected >
2. It doesn't support icons
3. val(["value1","value2"]) isn't reflected in the popup

Because of this programatically changing the selection isn't possible - even with material_select('destroy') and material_select() afterwards.

**Comment by MeMyselfI** [comment]
Additionally, val() doesn't deliver the actual selection... :-(

**Comment by TyrionGraphiste** [comment]
Hi,

Support for icons has been added after the select multiple support. So they just choose to not support icons for multiple select.

For select items two ways :
- With the selected options : $("select option:selected:not(:disabled)");
- With active class in the dropdown : $("ul#id li.active");

For selected option it's working but not really as intented :
- no checked checkbox
- no active class on the active option (li)

**Comment by acburst** [comment]
1. Tested locally, adding selected on a single option in a multiple select works, Adding multiple selected does not. (Will look into other issues mentioned by TyrionGraphiste) TODO

2. Images in select were just added and we wanted to release as soon as possible so it will be done in the future. TODO

3. Tested locally, if you do a .val() on the actual original select element, it will give you the correct value. You can also set the value on the original select element. Just make sure you are setting to the correct value. On our examples, our values are [1,2,3].

**Comment by rodofatos** [comment]
Hello, @acburst any idea when the fix for issue 1 will be fixed ? It's really somewhat critical at this moment to have an option to define what are selected options and have them checked in the dropdown. Thanks.

**Comment by rodofatos** [comment]
Also referring issue 3, currently in 97.3 the $(selector).val() returns an array of values that contains all the values that were checked at least once(even though now they are unchecked). 
![select values](https://cloud.githubusercontent.com/assets/12541574/11181667/d243f596-8c6c-11e5-9a85-9b90658a4be2.jpg)

**Comment by TyrionGraphiste** [comment]
I'm working on a fix which be pushed as a PR soon.

**Comment by Odonno** [comment]
I fixed it. I'll push it on a PR asap.

**Comment by Sabartius** [comment]
Another thing is the shown text, after you select several options. The optionstexts are ordered they way you clicked them. If you check first option5, then option3 and then option4 the diplayed text is "option5, option3, option4". A better way would be to preserve the order of my options, so that the text would be "option3, option4, option5".

**Comment by TyrionGraphiste** [comment]
This is not important.

**Comment by Odonno** [comment]
@Sabartius I agree with @TyrionGraphiste. I suppose you use a framework, or even without, you can reorder your array by writing a simple method.

**Comment by Sabartius** [comment]
It's not the array, but the text users see, whats bothering me. Let's assume the user selects options 5,3 and 4. After the Dropdown closes he sees the text : 5,3,4. He closes the application/dialog and reopens it. Then he would see the text 3,4,5 on the Dropdown. It may be a small thing for you, but (end-)users get really annoyed by such "problems". Especially when the ordering of the options is important.

**Comment by Odonno** [comment]
@Sabartius I see what you mean. Sure, I think it's better for the user. 

As an improvement, why not making accessible this text property ? To make it works like we need : 

* print options in order ("A", "B", "C)
* or print even number of values selected (3 items selected)

**Comment by damienwebdev** [comment]
Is there any movement on this? Are we supposed to consider #2321 as the goto fix?

**Comment by TyrionGraphiste** [comment]
I don't know for all issues but yes some have been fixed in the PR.

**Comment by whatda** [comment]
Hi, a fix would be appreciated. Thanks.

**Comment by tomscholz** [comment]
Is this issue fixed?

**Comment by popey456963** [comment]
@tomscholz I've got it on the latest version, so no, I don't think it's fixed.

![](https://puu.sh/weita/c8895ec596.png)

**Comment by popey456963** [comment]
Apparently #2321 never got merged?

**Comment by acburst** [comment]
Multiple select has been refactored and many bugs have been fixed in ec94158e750156c94ef8303dbf2245271e25b7b0. Coming soon in V1
