### ISSUE TITLE
Search bar issue on Chrome

### ISSUE THREAD

**Issue by gempain** [Dogfalo/materialize#3161]
Hello,

With Materialize v0.97.2, on Gooogle Chrome version 50.0.2661.102 (64-bit) for Mac OS X Yosemite 10.10.5, the search bar does not render correctly (screenshot taken straight from the official website):

![Image of Yaktocat](http://s32.postimg.org/7h72vdbph/Screen_Shot_2016_05_13_at_12_59_03.png)

Also, notice that on Safari 9.1, the search bar behaves strangely with the carret. When first focused, the carret fills 100% of the height, while when typing it fills half of the height. I think this comes from some `line-height` property somewhere.

First focus:

![First focus](http://s32.postimg.org/bo4re1ww5/Screen_Shot_2016_05_13_at_17_44_30.png)

While typing:

![While typing](http://s32.postimg.org/atj4urmx1/Screen_Shot_2016_05_13_at_17_44_41.png)

This is not new. I had the same problem with Materialize v0.97.0.

If I succeed finding a workaround, I'll let you know.

All the best, and thanks for the amazing work !

**Comment by wedneyyuri** [comment]
I can confirm this. It's working for firefox v37 but not working for Chrome v50

![image](https://cloud.githubusercontent.com/assets/7511692/15249141/7a4d2a8c-18f4-11e6-8d2a-fdbc3eff3ed6.png)

**Comment by gempain** [comment]
@wedneyyuri Thanks for confirming. I just updated my post to add another issue I have found (it's not as bad as the other one, but worth mentioning I think).

**Comment by acburst** [comment]
This issue was fixed and merged c129dc1.

It will be public in the next release or you could download our latest version

**Comment by wedneyyuri** [comment]
@acburst Do you have plans about the next release date?

**Comment by gempain** [comment]
Awesome :) Thanks for the great work !

**Comment by giuliolastra** [comment]
As a temporary fix you can add this style:
`.nav-wrapper, .nav-wrapper form, .nav-wrapper form .input-field{
	height: 100%;
}
`

**Comment by raphaelsoul** [comment]
the demo on the official website is not yet fixed.
![searchbox](https://cloud.githubusercontent.com/assets/8615787/15614019/53d0f978-2471-11e6-9dfc-823b7df8deb2.gif)

**Comment by gempain** [comment]
I think it won't be until the next release.

**Comment by fega** [comment]
Working in the latest version

**Comment by BjarnBronsveld** [comment]
This issue still persists in the latest 1.0 alpha release. Same behaviour as above.

**Comment by SmailyCarrilho** [comment]
This issue still happens on chrome and firefox in version 1.0.0-beta.

**Comment by acburst** [comment]
@SmailyCarrilho If you can provide a working codepen that reproduces this issue on the beta, please open a new issue with the codepen link

**Comment by hrajpal96** [comment]
![](https://i.imgur.com/Pe0STKG.jpg) This is a very strange issue that I'm facing on Chrome on Android.

**Comment by JavaDevilNZ** [comment]
Still seems to be broken on chrome. Looks fine on firefox. 

[Codepen example](https://codepen.io/anon/pen/dgWmzW)

I can fix this by adding this css

`.input-field input[type=search]{
    height: 64px  !important;
}`
