### ISSUE TITLE
fixed navbar not is darkened when the sidebar appears

### ISSUE THREAD

**Issue by matue** [Dogfalo/materialize#3393]
Hello.
When i push the sidebar-activate-button
![2016-07-21 19_20_27-somestuffer -](https://cloud.githubusercontent.com/assets/10290951/17026274/fb92187c-4f78-11e6-913d-48089698d06c.png)

body is darkened, but navbar no
![2016-07-21 19_21_20-somestuffer -](https://cloud.githubusercontent.com/assets/10290951/17026278/feb6f888-4f78-11e6-8ef2-7379fd5fac10.png)

**Comment by acburst** [comment]
Fixed in 26b82c130682b557a5e96f66c2e6f6d48821d4b0.

Let me know if that works

**Comment by matue** [comment]
sorry, but why this section of file test/html/overlayZindex.html:

<ul id="slide-out" class="side-nav">
      <li><a href="#!"><i class="material-icons">cloud</i>First Link With Icon</a></li>
      <li><a href="#!"><i class="material-icons">cloud</i>First Link With Icon</a></li>
      <li><a href="#!">Second Link</a></li>
      <li><div class="divider"></div></li>
      <li><a class="subheader">Subheader</a></li>
      <li><a class="waves-effect" href="#!">Third Link With Waves</a></li>
    </ul>
    <a href="#" data-activates="slide-out" class="button-collapse"><i class="material-icons">menu</i></a>

not in NAV tag?

<nav>
        <div class="nav-wrapper">
          <a href="#!" class="brand-logo">Logo</a>
          <ul class="right hide-on-med-and-down">
            <li><a href="sass.html">Sass</a></li>
            <li><a href="badges.html">Components</a></li>
          </ul>
        </div>
      </nav>

**Comment by acburst** [comment]
Its actually necessary if you are using a fixed nav because then the z-index won't be able to be higher

**Comment by matue** [comment]
Is it possible to make fixed nav darkened as do not fixed? But at the same time that the button which causes the sidebar was in it.

**Comment by acburst** [comment]
I'm not sure what you mean

**Comment by imzapatta** [comment]
**_z-position: 997_**, works for me.

**Comment by fega** [comment]
Closed due inactivity, feel free to reopen it if it is still necessary.
