### ISSUE TITLE
Uncaught TypeError: e.velocity is not a function(…)

### ISSUE THREAD

**Issue by rol4400** [Dogfalo/materialize#3812]
Using Laravel 5.3 with Gulp and Elixir. Materialize installed via npm. 

Error:
When mobile slidenav collapsed button is clicked:
![image](https://puu.sh/rSEV1/ff9841a403.png)

When dragging from side with mobile gesture to show the sidebar:
![image](https://cloud.githubusercontent.com/assets/12844299/19625547/0d8e78c4-995f-11e6-96a2-e19ab909335e.png)

Code:
window.$ = window.jQuery = require('jquery');
global.Tether = require('tether');
require('materialize-css');

$(".button-collapse").sideNav();

**Comment by kmmbvnr** [comment]
May be related issue - https://github.com/Dogfalo/materialize/issues/2661

**Comment by rol4400** [comment]
Yea, I fixed the issue by renaming the node_modules folder that was included in the package so that jquery wasn't included twice. You should really remove the jquery from the package.

**Comment by kduszczy** [comment]
I used @patombugua solution from https://github.com/InfomediaLtd/angular2-materialize/issues/20 to include materialize jquery instead of standard one, and it worked well.

`window.$ = window.jQuery = require('materialize-css/node_modules/jquery/dist/jquery.js'); require('materialize-css');`

**Comment by tomscholz** [comment]
https://github.com/Dogfalo/materialize/pull/3782#issuecomment-300734634

**Comment by DevChuckNorris** [comment]
I applied the patch locally and still getting the following errors:
Uncaught TypeError: $overlay.velocity is not a function

**Comment by tomscholz** [comment]
@DevChuckNorris Can you also check https://github.com/Dogfalo/materialize/pull/3552?

**Comment by T0miii** [comment]
@kduszczy strange enough but this was the only sullotion working for me. Thx  a lot friend.

ps: I hope they fix this asap. Its a grat library.

**Comment by kduszczy** [comment]
@T0miii I commented on 13 November so if its still not working the asap is not the proper term :smile:

**Comment by yammadev** [comment]
Any alternative for use Jquery v3.2 instead? @kduszczy solution works fine, but It would be better a cleaner approach, any idea? :confused:

**Comment by tomscholz** [comment]
Since #4774 materialize shouldn't use the it's own bundled version of jQuery anymore. Can someone check if the problem has been resolved in the latest version, so we can close this issue?
![bildschirmfoto 2017-06-27 um 18 31 37](https://user-images.githubusercontent.com/20381749/27599104-e71d0c0c-5b67-11e7-9e33-b6b803c7747a.png)

**Comment by yammadev** [comment]
@tomscholz It works perfect.

**Comment by tomscholz** [comment]
nice
