### ISSUE TITLE
Can't select options or scroll in select input on mobile

### ISSUE THREAD

**Issue by johhansantana** [Dogfalo/materialize#4200]
I can't seem to figure out why this happens, when I try to select an option on a select input on android mobile it doesn't select it, instead, it selects what's behind it. If I click on the select input and then again on the first options (which is on top of the input) the select will close and reopen like if I clicked the input instead of the option.

```html
<div className="input-field col s12 m6">
  <select
    name={`${categoryId ? 'categoryId' : 'category'}`}
    value={categoryId}
    onChange={handleChange}
  >
    <option value="" selected disabled>Seleccione una opción</option>
    {
      categories.map((category, index) => (
        <option key={index} value={category.id}>{category.name}</option>
      ))
    }
  </select>
  <label>Categoría</label>
</div>
```

![materializecsserror](https://cloud.githubusercontent.com/assets/9933887/22709296/b8b8ff00-ed4f-11e6-90cc-9ecbd9771a05.gif)

**Comment by hollsteinm** [comment]
+1 Just ran into this issue myself

**Comment by johhansantana** [comment]
Had to use `browser-default` class when viewing on mobile for the moment until I find a way to actually fix this or get some help.

**Comment by hollsteinm** [comment]
I just made it a full screen select with the following css:
`ul.dropdown-content.select-dropdown.active {
        position: fixed;
        top: 0;
        left: 0;
        width: 100%;
        height: 100%;
    }`

**Comment by briancwald** [comment]
+1 also had this issue.

**Comment by gewisser** [comment]
+1

https://youtu.be/vK4iIAR3Bi4

**Comment by milonas115** [comment]
https://jsfiddle.net/c6buv1j8/11/

**Comment by johhansantana** [comment]
@milonas115 woah! Pretty neat! I'll give it a try soon.

**Comment by gewisser** [comment]
@milonas115, thanks, works perfectly.

**Comment by milonas115** [comment]
@gewisser No problem, it also supports ajax requests if that is needed. My final version is a bit more extensive then the jsfiddle I made. Will be throwing it up on GIT once I finish all my tests.

**Comment by acburst** [comment]
Fixed in 1d94110

**Comment by cecemel** [comment]
Hi, was this change pushed in the 0.98 version? Furthermore, on the demo site ([http://materializecss.com/forms.html]), the select box doesn't work in mobile, i.e. chrome. Firefox is more or less ok (even though it displays weird)

**Comment by briancwald** [comment]
It was committed to master and will ship with the next release, can't push to a tagged release.

**Comment by cecemel** [comment]
ok thanks for the quick reply! Any idea when the next release  is coming?

**Comment by fanvyr** [comment]
Issue still happening in version 1.0.0.4 alpha.. (just mobile)
Anyone know a fix?

**Comment by Dogfalo** [comment]
See dd7f0d6fd4e6d7fb0cf820afbb1aedb0b57a8afd

**Comment by fanvyr** [comment]
using http://next.materializecss.com/select.html, am i wrong? How to implement that solution there? Sorry! Really love your project <3

**Comment by feraamorim** [comment]
It worked with the fix proposed by @cpelikan

**Comment by nicolegrafica** [comment]
> <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1.0, maximum-scale=1.0">

FUNCIONAA!!! MIL GRACIASSS @cpelikan

**Comment by Ross-Rawlins** [comment]
Hi I have tried all these supplied answers and it still doesnt let me scroll on mobile devices. Is there something I am missing?

**Comment by Darkmift** [comment]
@cpelikan Thank you so much <3
I love this framework its so elegant but its these tiny qwirks that I spend 70% of my time trying to solve.
Now if only someone can fix datepicker so its attribute actually do what they are supposed to do :P
