### ISSUE TITLE
Include Material icon font in distribution

### ISSUE THREAD

**Issue by jfix** [Dogfalo/materialize#5068]
Please consider distributing the following fonts in the `npm` module (and potentially other vectors):

* `MaterialIcons-Regular.woff2`
* `MaterialIcons-Regular.woff`
* `MaterialIcons-Regular.ttf`

Source: https://github.com/google/material-design-icons/tree/master/iconfont

They are being used to display Material Design icons irrespective of other fonts used.  For offline applications, or those behind firewalls, this would be really helpful. While I can understand the discussion around the exclusion of the `Roboto` font, I think there is less reason not to include the icon font.

An official `npm` module called `material-design-icons` exists, but it is about 60 Mb in size and contains all kinds of other assets.

I could see the fonts living here: `materialize-css/dist/fonts/material-icons`

Thanks for your consideration.

**Comment by DanielRuf** [comment]
You have to add them as dependency yourself, we do not bundle or require them.

**Comment by DanielRuf** [comment]
The size of the npm package does not really matter as you only include / import / require the needed files. The package contains the source files like every npm package.

**Comment by daggerok** [comment]
this is a bug in css in bower installed materialize package with css which is refers on

when I'm using

```html
<link rel="stylesheet" href="bower_components/materialize/dist/css/materialize.min.css">
```

is see in logs many 404 error for fonts. it's links on ../fonts which is not exists:
http://localhost:8080/bower_components/materialize/dist/fonts/roboto/Roboto-Bold.woff2
cause dist folder contains only js and css subfolders.

Of course bower users can include Roboto fonts manually, but they still will get such 404 errors unless you are referencing on any relative local paths to fonts `../fnots` materialize.min.css

*note: npm install materialize-css package works fine*

---
Cheers,
Maksim

**Comment by DanielRuf** [comment]
@daggerok this is not related to this issue, please create a new one. Also this might be already fixed in the latest releases.

**Comment by daggerok** [comment]
what do you mean?
how can I solve particular issue with bower materialize package?

**Comment by DanielRuf** [comment]
See https://github.com/Dogfalo/materialize/pull/5152

**Comment by daggerok** [comment]
@DaedalusDev, sorry, but I still can't understand how it can solve issue where font is configuring using relative path inside materialize.css

<img width="785" alt="screen shot 2017-08-30 at 18 03 00" src="https://user-images.githubusercontent.com/2445604/29879456-c621b7dc-8dad-11e7-8afb-95e612b45d25.png">

---
Redards

**Comment by DanielRuf** [comment]
The files were ignored with the wrong path. Bower removes ignored files. The font files are bundled with Materialize.
