### ISSUE TITLE
Bug when used with AMD (require.js)

### ISSUE THREAD

**Issue by max1011** [Dogfalo/materialize#634]
the company i am working with likes material design, so i told them about materialize, and they said ok use it , no problem , but currently i am stuck with this so please help !

when i try to require materialize , no errors are shown, but when i actually use it with jquery, it tells me that the method that i am trying to use on that element is undefined
here is my code (js):

``` javascript
requirejs.config({
  paths: {
    'materialize': '../../bower_components/materialize/dist/js/materialize',
    'jquery': '../../bower_components/jquery/dist/jquery'
  },
  shim: {
    'materialize': {
      deps: ['jquery']
    },
    'jquery': {
      exports: '$'
    }
  }
});

require(['jquery', 'materialize'], function($) {
  $('select').material_select();
});
```

Screen Shot: 
![image](https://cloud.githubusercontent.com/assets/6626011/6079567/92fbe448-ae0f-11e4-94e6-222736a11ee0.png)

**Comment by Dogfalo** [comment]
Currently there are some problems with using materialize + requirejs. We will look into this when we can.

**Comment by max1011** [comment]
i solved this on my own, there is an issue with the buttons, but other than that it works fine, i will post the fix soon

**Comment by Dogfalo** [comment]
Great, looking forward to seeing it.

**Comment by max1011** [comment]
@Dogfalo , I just fixed it all up it works 100% Love It, i want to ask you if i post this solution will i be one of the contributors on this project ??

**Comment by Dogfalo** [comment]
Yes if you make a pull request and we accept it.

**Comment by max1011** [comment]
OK I've got my code on a separate file, i will add it to the project itself and i'll make a pull request, so all what's left is to modify the source code, and hopefully you'll like it.

**Comment by max1011** [comment]
To fix this here is what your file should look like, @Dogfalo please add this to the documentation so that if there is anyone that uses require knows what to do and you certainely don't want to lose them
```javascript
requirejs.config({
  paths: {
    'materialize': '../../bower_components/materialize/dist/js/materialize',
    'jquery': '../../bower_components/jquery/dist/jquery',
    'velocity': '../../bower_components/materialize/js/velocity.min',
    'hammerjs': '../../bower_components/materialize/js/hammer.min'
  },
  shim: {
    'materialize': {
      deps: ['jquery', 'hammerjs', 'velocity']
    }
  }
});


// Require both jquery and materialize (materialize will load other stuff that is needed)
require(['jquery', 'materialize'], function($) {

  $(function() {
    // Dom is ready
    // this is very important for some components like material_select

    // initialize some components (this is what i need, it can be anything)
    $('select').material_select();
    $(".button-collapse").sideNav();
    $('ul.tabs').tabs();

    // display the waves effect
    // waves is already loaded by materialize
    // just initialize it to make it work (if you don't it won't work)

  });

  // the dropdown is the first thing we need (and it doesn't load right away)
  // so we initialize it as soon as possible
  // if this causes an issue
  // move it to the "documnent ready" function
  $(".dropdown-button").dropdown();
});
```
**Note:** this code doesn't work with the current repo it will work after my pull request #653 is accepted

**Comment by creatifDynamics** [comment]
I'm using the configuration above but have this error when using a button or dropdown:
Uncaught ReferenceError: scrollFire is not defined

**Comment by max1011** [comment]
this of course was temporarily i am working on a permanent solution, for a simple fix in your case just add a path to scrollfire in require config paths like so (this was for me change it work with your paths config):
```javascript
'scrollfire': '../../bower_components/materialize/js/scrollFire'
```
and then add it to the deps of materialize , if you have used the same code then it should look something like this 
```javascript
deps: ['jquery', 'hammerjs', 'velocity', 'scrollfire']
```
hope that helps @creatifDynamics !!

**Comment by creatifDynamics** [comment]
Thanks. I already figured this out and used it. Still, if I don't explicitly use scrollFire I don't expect an error about. I'll just wait for your fix because it's not blocking. Thank you !

**Comment by max1011** [comment]
your welcome @creatifDynamics , don't worry about the fix i have to do it because like i said i am working with a company and i have to fix it !!

**Comment by max1011** [comment]
hey @creatifDynamics , i had it fixed you can checkout my solution and try it out #794 , if it works please let me know , (Note that there is no need to load the dependencies just add jquery as a dep if needed)

**Comment by husterk** [comment]
I am also running into similar issues when trying to load materialize. I tried to follow the suggestions above but in the version that I downloaded from the Materialize site (v0.95.3) it seems as though Hammer, Velocity, Scrollfire, etc... have been merged into a single materialize.js file so I don't think that I can reference them independently in requireJS definition. I am seeing the following errors when attempting to use materialize and also noticing that the UI loads but does not fully function (JS based features are not working).

### Errors
* ReferenceError: scrollFire is not defined
* Error: Mismatched anonymous define() module: function ($, Hammer) {...

### My RequireJS Definition File
```javascript
requirejs.config({
    paths: {
        'text' : '../lib/require/text',
        'durandal' :'../lib/durandal/js',
        'plugins' : '../lib/durandal/js/plugins',
        'transitions' : '../lib/durandal/js/transitions',
        'knockout' : '../lib/knockout/knockout-3.1.0',
        'jquery' : '../lib/jquery/jquery-2.1.3',
        'materialize' : '../lib/materialize/js/materialize'
    },
    shim: {
        'materialize': {
            deps: ['jquery']
        },
        'jquery': {
            exports: '$'
        }
    }
});
```

**Comment by max1011** [comment]
Well check out this solution #794 and this will fix the issue, but it's not yet merged into master what you can do to fix temporarily is just load scrollfire as a dependency you can see that when i told creatifDynamics about it, so stick to that until the fix is merged into master

**Comment by husterk** [comment]
@max1011 - I downloaded HammerJS, VelocityJS, and the JQuery.ScrollFire plugin into my project and then referenced each of these libs in my RequireJS config definition. However, I am still seeing the exact same errors. I am somewhat new to using RequireJS and this is my first attempt to work with the Materialize UI framework so any guidance would be appreciated.

### Updated RequireJS Configuration
```javascript
requirejs.config({
    paths: {
        'text' : '../lib/require/text',
        'durandal' :'../lib/durandal/js',
        'plugins' : '../lib/durandal/js/plugins',
        'transitions' : '../lib/durandal/js/transitions',
        'knockout' : '../lib/knockout/knockout-3.1.0',
        'jquery' : '../lib/jquery/jquery-2.1.3',
        'materialize' : '../lib/materialize/js/materialize',
        'hammer' : '../lib/hammer/hammer.min',
        'velocity' : '../lib/velocity/velocity.min',
        'scrollFire' : '../lib/scrollfire/jquery.scrollfire.min'
    },
    shim: {
        'materialize': {
            deps: ['jquery', 'hammer', 'velocity', 'scrollFire']
        },
        'jquery': {
            exports: '$'
        }
    }
});
```

**Comment by max1011** [comment]
ok, so i inspected materialize a bit and it turns out that scrollfire is being generated on the wrong spot, meaning it's being used before it even exists so i changed the gruntfile to generate the new modified file and it seems to work, all of these changes are on my own fork #794, so please try out the new solution and tell me if it works @husterk

**Comment by T00rk** [comment]
I had the same problem. I downloaded the version from your repository and that works.
Thanks a lot.

**Comment by creatifDynamics** [comment]
When are you guys planing to put it in master ?

**Comment by max1011** [comment]
Well, we need @Dogfalo to merge my repo into this one, so please @Dogfalo there you have people saying that my solution works ( i am one of them)  so please merge!

**Comment by Dogfalo** [comment]
There was also a report that it didn't work

**Comment by max1011** [comment]
I fixed it like a few days ago!, it wasn't working but now it is

**Comment by max1011** [comment]
please everyone that have tried my newest updates to the fix and have it working or not working, comment out on the pull request #794 if it works or not if not tell us what is your problem!!

**Comment by max1011** [comment]
@T00rk what is your problem??,  what is logged in the console??

**Comment by husterk** [comment]
I just tested out the changes from @max1011 and they worked for me. Thanks! Hopefully these changes will get merged in soon.

**Comment by T00rk** [comment]
I've got a "Load timeout for modules: materialize"

**Comment by max1011** [comment]
There was a script error in one of the listed modules. If there is no script error in the browser's error console, and if you are using Firebug, try loading the page in another browser like Chrome or Safari. Sometimes script errors do not show up in Firebug.

**Comment by max1011** [comment]
@T00rk did you reference materialize from the bin directory??

**Comment by T00rk** [comment]
@max1011 Yes that's ok now

**Comment by Harko33** [comment]
Hi, 
I had a similar issue when using the "toast" function : I got a message "hammer is not a function". I tried the fix from @max1011 and it's OK now. I think it can be merged in master branch.

**Comment by max1011** [comment]
Great to hear that the fix is working, thanks everyone! :)

**Comment by jfpwork** [comment]
Dont know why but 
moving scrollFire = function(){...} before 
$(document).ready(function() {..} at line 2966 of Materialize v0.95.3, 
so you get error Uncaught ReferenceError: scrollFire is not defined at line 2995

**Comment by max1011** [comment]
With amd the ready event might fire before amd runs (it uses a different event) and issues could happen so that's why this happens with require.js and doesn't happen with the normal usage of materialize

**Comment by patriciapineda** [comment]
Your solution works!

**Comment by max1011** [comment]
Thanks @patriciapineda, i hope it will be in master soon!

**Comment by ekarudianto** [comment]
hmmmm after did some reading I think I faced the same issue 

[here] (https://github.com/Dogfalo/materialize/issues/1212)

**Comment by max1011** [comment]
@ekarudianto use the repo that was use in pull request #794 instead of the original project which is my own repo, you can read how it was fixed if you want to, it's a bit complex, so just use the repo and include the materialize file from the bin directory and there is no need to anyother deps, LMK if this works!

**Comment by ekarudianto** [comment]
ummm I think it didn't work you could read my last comment [here] (https://github.com/Dogfalo/materialize/issues/1212)

**Comment by sirugh** [comment]
I just discovered a similar issue using the [require-handlebars-plugin(https://github.com/SlexAxton/require-handlebars-plugin).

Haven't tried @max1011s fix yet, will update after.

**Comment by kkoch986** [comment]
I had some luck by adding the following to my gruntfile which builds materialize:
```javascript
file_append: {
      dist: {
        files: [
          {
            prepend: "require(['jquery', 'hammerjs', 'velocity'], function($, Hammer, Velocity) { define.amd = false;",
            append: "});",
            input: 'dist/js/materialize.js',
            output: 'dist/js/materialize.js'
          }
        ]
      }
    },
```

then just using it without requires shim config. Also removed the hammer.min and verlocity.min and loaded them separately using the following config:

```javascript
requirejs.config({
	baseUrl: 'src/js',
	wrapShim:true,
	paths: {
		"jquery" : "vendor/jquery",
		'velocity': './materialize/velocity.min',
		'hammerjs': './materialize/hammer.min',
		'materialize': '../../dist/js/materialize',
	},
});
```

hope that helps someone, i was trying to build this into a single file using rjs and was having all kinds of problems, this seemed to be the best working way. Havent tested out all the functionality but waves and hammer seem to be working ok.

**Comment by max1011** [comment]
@kkoch986 , this is the method i am using and it works, but let me tell you one thing, it's not using the benefit of require.js, and it will also expose the variables to the window object (meaning they will be global), but we use require.js in order to prevent global scope pollution, so that's why i was working on a new solution which is creating a separate file for amd, e.g. materialize.amd.js which requires all the dependencies in an async way, so you can remove any deps that you don't need from there and it will still work perfectly, and i optimize it and make it one file (one request) with r.js optimizer, i know it's kind of difficult and full of bugs but i did it with no bugs (after facing lots of bugs) and it works, i tested it today you can use any of both (the optimized version and the original one), and the user can customize the original file and load only what he needs (he also needs to run r.js to generate the new file) and it will always work ! , so i will be posting the new solution with a guide soon, i will give you a heads up when i do that

**Comment by max1011** [comment]
@kkoch986 i have it ready at [materialize-AMD](https://github.com/max1011/materialize-AMD), all you need to do to use is just use the materialize.amd.js from the dist directory, you can see what i did there, i added the materialize amd file and a config file for r.js to concatenate all of the file together in AMD way, the original file is in /js, and to run r.js, all you have to do is to run these commands:
```bash
cd js
r.js -o app.build.js 
``` 
if r.js is not available just download [r.js-require optimizer](https://github.com/jrburke/r.js) 
anytime you add a new module you have to add it to the materialize.amd.js and run r.js, that's all, it's a way better solution now the user can customize this file and run r.js to get the custom file with all the modifications and there is no global scope pollution so problem solved, when @Dogfalo sees this, i will propose that solution rather than the old one (after some people try it out and confirm it's working)

**Comment by kkoch986** [comment]
@max1011  looks cool, ill try to check it out asap, for now what i have works well enough so im gonna move on thanks!

**Comment by max1011** [comment]
your welcome buddy!

**Comment by rheaditi** [comment]
Hi!
@max1011 I'm new to Javascript as a whole so please bear with me if these are silly :P

So, I've used your dist/materialize.amd.js in my project and included in the "main" as:

```javascript
requirejs.config({
    baseUrl: 'js/',
    paths: {
        'jquery': 'jquery-2.1.4',
        'materialize': 'materialize.amd'
    },
    shim: {
        'jquery': {
            exports: '$'
        },
        'materialize': {
            deps: ['jquery']
        }
    }
});

require(['jquery', 'materialize'],
function ($, materialize) {
    
    $(".button-collapse").sideNav();
    $('.parallax').parallax();
    $('.dropdown-button').dropdown();    

});
```

I get the following errors in the console:
* Uncaught ReferenceError: Materialize is not defined(anonymous function) @ materialize.amd.js:1
* main.js:20 Uncaught TypeError: $(...).sideNav is not a function

**Comment by max1011** [comment]
@rheaditi well that was my fault i tested the changes on an old version of materialize, but added them on a new one, so i re-modified the code to work with the new version, try pulling now and LMK if it work!

**Comment by rheaditi** [comment]
Hi, @max1011 . Thanks for replying!
Used the materialize.amd.js file (modified 2 days ago). Still getting:
 * Uncaught TypeError: $(...).sideNav is not a function

"main" as follows, removed materialize:

```javascript
requirejs.config({
    baseUrl: 'js/',
    paths: {
        jquery: 'jquery-2.1.4',
        materialize: 'materialize.amd'
    },
    shim: {
        'jquery': {
            exports: '$'
        },
        'materialize': {
            deps: ['jquery']
        }
    }
});

require(['jquery', 'materialize'],
function ($) {
    $(".button-collapse").sideNav();
    $('.parallax').parallax();
    $('.dropdown-button').dropdown();    

});
```

**Comment by max1011** [comment]
Did you pull the new code?

**Comment by vuza** [comment]
@rheaditi I just got it up and running by including every single file in /js from @max1011 materialize-amd repo, except from materialize.amd directly into my require.config.
```
require.config({
    baseUrl: 'myBaseUrl',

   paths: {
        /** my stuff .. */
       
       'hammerjs': 'vendor/materialize/hammer.min',
        'jquery.easing': 'vendor/materialize/jquery.easing.1.3',
        'velocity': 'vendor/materialize/velocity.min',
        'picker': 'vendor/materialize/date_picker/picker',
        'picker.date': 'vendor/materialize/date_picker/picker.date',
        'waves': 'vendor/materialize/waves',
        'global': 'vendor/materialize/global',
        'animation': 'vendor/materialize/animation',
        'collapsible': 'vendor/materialize/collapsible',
        'dropdown': 'vendor/materialize/dropdown',
        'leanModal': 'vendor/materialize/leanModal',
        'materialbox': 'vendor/materialize/materialbox',
        'tabs': 'vendor/materialize/tabs',
        'sideNav': 'vendor/materialize/sideNav',
        'parallax': 'vendor/materialize/parallax',
        'scrollspy': 'vendor/materialize/scrollspy',
        'tooltip': 'vendor/materialize/tooltip',
        'slider': 'vendor/materialize/slider',
        'cards': 'vendor/materialize/cards',
        'buttons': 'vendor/materialize/buttons',
        'pushpin': 'vendor/materialize/pushpin',
        'character_counter': 'vendor/materialize/character_counter',
        'toasts': 'vendor/materialize/toasts',
        'forms': 'vendor/materialize/forms',
        'scrollFire': 'vendor/materialize/scrollFire',
        'transitions': 'vendor/materialize/transitions',
        'jquery.hammer': 'vendor/materialize/jquery.hammer'
    },

   shim: {
       /** my stuff .. */
   
      'jquery.easing': {
            deps: ['jquery']
        },
        'animation': {
            deps: ['jquery']
        },
        'jquery.hammer': {
            deps: ['jquery', 'hammerjs', 'waves']
        },
        'global': {
            deps: ['jquery']
        },
        'toasts': {
            deps: ['global']
        },
        'collapsible': {
            deps: ['jquery']
        },
        'dropdown': {
            deps: ['jquery']
        },
        'leanModal': {
            deps: ['jquery']
        },
        'materialbox': {
            deps: ['jquery']
        },
        'parallax': {
            deps: ['jquery']
        },
        'tabs': {
            deps: ['jquery']
        },
        'tooltip': {
            deps: ['jquery']
        },
        'sideNav': {
            deps: ['jquery']
        },
        'scrollspy': {
            deps: ['jquery']
        },
        'forms': {
            deps: ['jquery', 'global']
        },
        'slider': {
            deps: ['jquery']
        },
        'cards': {
            deps: ['jquery']
        },
        'pushpin': {
            deps: ['jquery']
        },
        'buttons': {
            deps: ['jquery']
        },
        'transitions': {
            deps: ['jquery','scrollFire']
        },
        'scrollFire': {
            deps: ['jquery', 'global']
        },
        'waves': {
            exports: 'Waves'
        },
        'character_counter': {
            deps: ['jquery']
        }
   },

    deps: ['jquery', /** my stuff ... */]
}

require([
        /** my stuff ... */

       'jquery.easing',
        'animation',
        'velocity',
        'hammerjs',
        'jquery.hammer',
        'global', // very important do not remove!
        'collapsible',
        'dropdown',
        'leanModal',
        'materialbox',
        'parallax',
        'tabs',
        'tooltip',
        'waves',
        'toasts',
        'sideNav',
        'scrollspy',
        'forms',
        'slider',
        'cards',
        'pushpin',
        'buttons',
        'scrollFire',
        'transitions',
        'picker',
        'picker.date',
        'character_counter'],
    function(App){
        /** All materialize functions available here! */
        App.start();
    }
);

**Comment by rheaditi** [comment]
@max1011 
Yes, I pulled your new code. I just copied  "dist/js/materialize.amd.js" from your repo to my own project. 
Double checked just now!

@vuza I'll give that a try, if all fails!

**Comment by max1011** [comment]
Try using the entire repo instead of just that file because yoir version might be a little different

**Comment by max1011** [comment]
well i will add an example file there on how to use and try running that, i will give you a heads up when i do

**Comment by max1011** [comment]
it's done, i added a AMDtest.html to the repo, try cloning and open this file, tell me if it works (if there is no errors and all is displayed in the right way)

**Comment by max1011** [comment]
there is a new issue with their new code, in materialize, they are relying on the presence of the Materialize global variable in global.js which is a big mistake, AMD & commonjs support is needed there is alot of AMD & commonjs users out there so not only the global js file has to be fixed but also the other files that rely on the presence of Materialize globally, to do that we need to check if amd or commonjs support and if so the corresponding function should run which is an IFFEE argument function and the function that is called has that function as an argument i can help any time, if there is anyone that wants to help i would be happy !! and i almost forgot to thank everyone for their support !!

**Comment by ronakkhunt** [comment]
@max1011 
Hi, I cloned you repo and built 'materialize.amd.js', and used it in my project.
But when i try to use openModal() function. it gives following error.

>>Uncaught TypeError: s.velocity is not a function 

I tried with some changes in app.build.js, but could not figure out what going wrong. and also AMDtest.html is working fine.

**Comment by max1011** [comment]
Try adding velocity as a dependency to the modal file it might be called modal but i am not sure do that in the app config and rebuild you will find some instructions on hiw to do it in the comments above, or just to debug use the materialize amd file in the js directory not in dist and change it there and see if it works, anyways i will take a look at it asap for now try that if not tell me and i will help you

**Comment by ronakkhunt** [comment]
@max1011 
Thanks for replying.
I have already tried that(file is named "leanModal.js") and it's giving same error. I am using this generated  'materialize.amd.js' with other require config file that I have in my project. Other functions of materialize are working fine.

**Comment by max1011** [comment]
ok this means i have to diagnose the problem and i will give you a heads up when i do

**Comment by ugopozo** [comment]
I got it to work based on @vuza's approach, but instead of modifying my own r.js config, I just "rebuilt" Materialize's Javascript using r.js, without having to modify any code from either Materialize itself or my own application.

The current issue is due to the fact that Materialize mixes up both AMD-aware and non-AMD libraries, and, from what I can gather, Grunt just concats them together, without any analysis regarding namespaces and whatsoever. Using r.js instead of Grunt to build Materialize and shimming the non-AMD libraries just works - it spits outs a fully-AMD aware version of Materialize.

It just needs a "main" file, to load all dependencies when imported:

```javascript
require(['global', 'animation', 'buttons', 'cards', 'character_counter',
		'collapsible', 'dropdown', 'forms', 'hammerjs', 'jquery.easing',
		'jquery.hammer', 'jquery.timeago', 'leanModal', 'materialbox',
		'parallax', 'picker', 'picker.date', 'pushpin', 'scrollFire',
		'scrollspy', 'sideNav', 'slider', 'tabs', 'toasts', 'tooltip',
		'transitions', 'velocity', 'waves'],
	function (Materialize) {
		return Materialize;
	}
);
```

and a build file for r.js:

```javascript
({
	baseUrl: "bower_components/materialize/js",
	name: "../../../materialize",
	out: "lib/materialize.amd.js",
	paths: {
		'jquery': "../../jquery/dist/jquery",
		'animation': 'animation',
		'buttons': 'buttons',
		'cards': 'cards',
		'character_counter': 'character_counter',
		'collapsible': 'collapsible',
		'picker': 'date_picker/picker',
		'picker.date': 'date_picker/picker.date',
		'dropdown': 'dropdown',
		'forms': 'forms',
		'global': 'global',
		'hammerjs': 'hammer.min',
		'jquery.easing': 'jquery.easing.1.3',
		'jquery.hammer': 'jquery.hammer',
		'jquery.timeago': 'jquery.timeago.min',
		'leanModal': 'leanModal',
		'materialbox': 'materialbox',
		'parallax': 'parallax',
		'pushpin': 'pushpin',
		'scrollFire': 'scrollFire',
		'scrollspy': 'scrollspy',
		'sideNav': 'sideNav',
		'slider': 'slider',
		'tabs': 'tabs',
		'toasts': 'toasts',
		'tooltip': 'tooltip',
		'transitions': 'transitions',
		'velocity': 'velocity.min',
		'waves': 'waves'
	},
	shim: {
		'jquery': { exports: "$" },
		'animation': ['jquery'],
		'buttons': ['jquery'],
		'cards': ['jquery'],
		'character_counter': ['jquery'],
		'collapsible': ['jquery'],
		'dropdown': ['jquery'],
		'forms': ['jquery', 'global'],
		'global': { deps: ['jquery'], exports: "Materialize" },
		'jquery.easing': ['jquery'],
		'jquery.hammer': ['jquery', 'hammerjs', 'waves'],
		'jquery.timeago': ['jquery'],
		'leanModal': ['jquery'],
		'materialbox': ['jquery'],
		'parallax': ['jquery'],
		'pushpin': ['jquery'],
		'scrollFire': ['jquery', 'global'],
		'scrollspy': ['jquery'],
		'sideNav': ['jquery'],
		'slider': ['jquery'],
		'tabs': ['jquery'],
		'toasts': ['global'],
		'tooltip': ['jquery'],
		'transitions': ['jquery','scrollFire'],
		'waves': { exports: 'Waves' }
	},
	optimize: "none",
	exclude: ["jquery"],
	include: ['global', 'animation', 'buttons', 'cards', 'character_counter',
		'collapsible', 'dropdown', 'forms', 'hammerjs', 'jquery.easing',
		'jquery.hammer', 'jquery.timeago', 'leanModal', 'materialbox',
		'parallax', 'picker', 'picker.date', 'pushpin', 'scrollFire',
		'scrollspy', 'sideNav', 'slider', 'tabs', 'toasts', 'tooltip',
		'transitions', 'velocity', 'waves']
})
```

Assuming one used bower to install materialize, just name the main file "materialize.js" (or change the "name" property in the config file to match whatever name you'd like), put both files in the same directory, create a "lib" directory (or modify the "out" property) and build it with ```r.js -o <config_file_name>.js```.

None of this should be difficult for anyone with minimal experince using r.js (and well, if you want materialize to work with require.js it stands to reason that you're somewhat familiar with require.js). Afterwards, you can use the generated file as you'd use any AMD-enabled library (it imports materialize's global object Materialize, and you need to require it in whatever files you need materialize's specialized functions).

One would also need to pay attention to changes in the files in the ```js``` folder from materialize's source, since you'd have to add new files to the "path" (optionally), "shim" (if the new file is not AMD-aware) and "include" (optionally, but it doesn't hurt) config options, and to the "main" list of requirements (obligatoryly).

**Comment by max1011** [comment]
True, and that's what i did exactly but still there are some issues with some functionalities, so i will be testing the code more and more to recognize all the issues and fix it all up,hopefully i will be able to do that very soon

**Comment by max1011** [comment]
@ronakkhunt hi just wanted to let you know that the modal issue was fixed, please confirm it works!, and for everyone else who is having this issue can try it too

**Comment by noodny** [comment]
I've made a small node module, which does everything according to @ugopozo comment. Perhaps someone else will find it useful.
https://github.com/noodny/materializecss-amd

**Comment by gracesusanchen** [comment]
Hi there, I've been using @ugopozo's solution, but it hadn't work for Materialize.toast(), which throws a "Hammer is undefined" error.

I've overcome this by manually modifying the build materialize.amd.js file. I've moved the `Materialize.toast` definition into its `define` block
```javascript
define(['toasts'], ['hammerjs', 'velocity'], function(Hammer, Vel) {
    Materialize.toast = ...;
});
```
Thought I'd report it here, cheers!

**Comment by tmedanovic** [comment]
Thanks @ugopozo and @noodny for fix, worked like charm! 
@noodny btw.
 I was getting an error at 
 "prestart": "node_modules/bower/bin/bower install",

So I just removed prestart and manually ran brower install, then it worked.

**Comment by akwuh** [comment]
@kkoch986 your solution is the best! Thanks great!

**Comment by max1011** [comment]
@akwuh this was my idea initially but this is totally wrong, cause you are using AMD to prevent global variables and when u set define.AMD to false all variables become global, and now AMD is not useful for u, if u use it normally it will be the same so this is not a solution , the apropriate solution is to do it the AMD way, which is what i've also done in my [Materialize-AMD](https://github.com/max1011/materialize-AMD) repo

**Comment by akwuh** [comment]
@max1011 I suppose (using your idea) not to just turn `define.amd` to `false`, but to return its initial value after `Materialize` will be created in global scope. Am I wrong?
P.S. I agree with u that your solution is right, but it doesn't work for me, I juse can't use `Materialize.toast()` due to error `Hammer is not defined`

**Comment by max1011** [comment]
@akwuh then just add Hammer as a dep. to toast , or just make Hammer only Global while keeping the other the same, the issue here is the guys that added Materialize depended on Hammer to be global and tha's a really bad mistake, they didn't account for AMD nor commonjs they just agnored it that entire file needs refactoring and alot of work just to support AMD and commonjs, and it's always a bad idea to assume things Materialize is gaining popularity and it's a must to account for all the different uses of this library it's used to make things easier and not harder !, we can just put the same plugins they use in our code without using materialize it self bt we use it cause it have all what we need for material design so really it's just essential to support AMD and commonjs, which is actually a must for scalable apps, if they didn't do it we can't just build scalable apps!

**Comment by 39dotyt** [comment]
Voting up for the issue. I think that the best solution is a code refactoring to implement materialize in UMD or at least optionally compatible with AMD.

**Comment by max1011** [comment]
yes, they must do it from 0 and not a workaround they must always account
for all different kinds of uses not just one
the global thing (turning define.amd to false) just makes the library act
as if we used it globally so it should work , i don't know why u get this
error, it usually works
hope they can fix it soon, i am sorry but i have more important stuff than
materialize so i hope they can fix it ASAP

**Comment by AbhaySuchak** [comment]
i am using materialize css for my site for design purpose and i am using angularjs to provide fair flexibility to my site but some property of materialize(Select,date-picker,radio-button) did not insert while inserting query it takes blank values from ng-model and when i am talking about radio button so it takes 2nd value when i select 1st or reverse.

So it is my straight Question is..

what is the scope of using materialize or material design or angular material with AngularJS because my priority is to use AngularJS with any of above google design.

please responds as soon as possible

**Comment by AbhaySuchak** [comment]
i am using materialize css for my site for design purpose and i am using angularjs to provide fair flexibility to my site but some property of materialize(Select,date-picker,radio-button) did not insert while inserting query it takes blank values from ng-model and when i am talking about radio button so it takes 2nd value when i select 1st or reverse.

So it is my straight Question is..

what is the scope of using materialize or material design or angular material with AngularJS because my priority is to use AngularJS with any of above google design.

please responds as soon as possible


@max1011

**Comment by max1011** [comment]
@AbhaySuchak , well i am actually using materialize with alot of other libraries (one of them is angular) i had alot of bugs yes but the thing is i always can make it work and fix the source code, you can make it work if you are smart enough you can get your self around but i know how hard it is because i've tried, all of this is about materialize not the angular material project, for that one i know it also has alot of problems , if you want to start using material design then do it for small projects if it's something big it's not good for a lot of reasons (performance, bugs with different implementations, etc..) i mean it's not as flexible as you want it to, my advice for any of your future projects , if there is a project that is less that v1 and it still not that much stable like materialize, then always try to avoid these kind of libraries it will save you hours of fixing bugs and at some point that bug looks like it will never be fixed and you will be forced to switch so switch from the start to something  else (you don't have to switch now it's just for the future)

**Comment by vaibhav93** [comment]
Can somebody please tell finally how it works ? How do I use materialize-AMD repo

**Comment by max1011** [comment]
@vaibhav93 clone the repo, and use the materialize.amd.js from the dist directory as 'Materialize', and require it normally

**Comment by vaibhav93** [comment]
@max1011 Thanks man ! Works flawlessly

**Comment by max1011** [comment]
@vaibhav93 the way those plugins are loading is asynchronous , meaning that there is a problem in the order in which they are loaded, so if you load them synchronously it will block script execution and downloading until it's done downloading and executing, then it continues to run the other materialize script which requires to to run at some point , if they are loaded before it wants it it's ok and that's why if you load them manually it works, i should change a bit of how those modules are loaded in a bit more effective way so that we can make sure when materialize wants a certain function from another file it's already loaded, all of this means the entire problem is moving from sync to a-sync (from normal to AMD way), async is known to create alot of problems because of the way it behaves, so i will test your code and fix it as soon as i can, for now stick with your solution .

**Comment by vaibhav93** [comment]
Okay. Finally managed to get things working. For those facing issues with waves not working, you need to initialize wave using Waves.displayEffect( )  . Wasted entire day to figure this out since the latest version of waves.js (0.7.4) uses Waves.init() whereas materialize is still making use of an older waves.js version (0.6.4) which uses the displayEffect function (now deprecated in latest waves).
Posting working gists
main.js (require config file) https://gist.github.com/vaibhav93/fe28db799dc441c7ae6b 
app,js https://gist.github.com/vaibhav93/5f16b815b70051dc7bba

**Comment by max1011** [comment]
@vaibhav93 for waves i mentioned this (how to make waves work if it's not already initialized) a lot if you search for it , you just first search for someone else who asked, i answered the question about it, anyways it good to know you figured it out

**Comment by dirkpennings** [comment]
When I'm reading this topic, is there a solution provided by the Materialize team already? Since the issue was created in February I was curious if I could easily use it with requirejs already.

**Comment by max1011** [comment]
@dirkpennings you can use my repo [materialize-AMD](https://github.com/max1011/materialize-AMD), use the materialize.amd.js from the dist directory as 'Materialize', and require it normally,
for any errors you can fix it manually, or you can use the manual solution , there is no official amd version of materialize from materialize team, hope this helps

**Comment by dirkpennings** [comment]
@max1011 thanks for mentioning. How often are you planning to update that repo? Because the last commit was on July 14 and it currently uses materialize version 0.96.1 so that's of no use to me (because of some bug fixes in the more recent versions of materialize)

**Comment by max1011** [comment]
well, i will try to update it in the next few weeks , cause there is alot
of changes that i have to make, i think about two weeks or more is enough
unless i face a major issue, hope you get it

**Comment by FabioNgo** [comment]
sorry, is the latest version of materialize css supported requirejs ?

**Comment by max1011** [comment]
The offical materialize css repo doesn't support require js, but you can
see we are all working to fix it and using our own solutions with some
workarounds, hope it helps

**Comment by dptole** [comment]
I'm using https://github.com/max1011/materialize-AMD so that I can have AngularJS/RequireJS/MaterializeCSS together. I had problems with `Materialize.toast` but I solved it by:

1 - Requiring hammer.js as a separate file. Necessary to expose the Hammer function.
```html
<script src="hammer.js">
```
2 - Exposing `$.Velocity` to the global scope.
```js
window.Vel = $.Velocity;
```

**Comment by ccloli** [comment]
I'm using the latest Materialize (0.97.5) with [curl.js](https://github.com/cujojs/curl) (AMD), then I tried  using `$(...).sideNav()` and occurred an error `dragTarget.hammer is not a function`.

Luckily, I deleted some lines of `define` and it works fine now. Here are my steps (with offical [0.97.5](https://github.com/Dogfalo/materialize/blob/14f272a58e3524623e330c736d3a9b88ab500cc2/dist/js/materialize.js), not the unoffical-AMD version):



1 . Delete this part at Line 232:
```js
"object"==typeof module&&"object"==typeof module.exports?module.exports=a():"function"==typeof define&&define.amd?define(a):
```
2 . Delete this part at Line 234:
```js
typeof define==ka&&define.amd?define(function(){return ea}):"undefined"!=typeof module&&module.exports?module.exports=ea:
```
3 . Delete Line 235~239, 241:
```js
    if (typeof define === 'function' && define.amd) {
        define(['jquery', 'hammerjs'], factory);
    } else if (typeof exports === 'object') {
        factory(require('jquery'), require('hammerjs'));
    } else {
        factory(jQuery, Hammer); // DON'T delete this line
    }
```
4 . Add this part to show waves (see https://github.com/Dogfalo/materialize/issues/634#issuecomment-154833830) :
```js
require(['jquery']).next(['materialize'], function(Materialize){
    Waves.displayEffect();
});
```

**Comment by lmadrilejos** [comment]
Hello Everyone,

I'm having the same issue here, I have tried doing almost all of the suggested steps on this post but still I'm having the same issue. I couldn't include or define materialize inside my pageview, please help... many thanks....

**Comment by ccloli** [comment]
@lmadrilejos How about [my solution](https://github.com/Dogfalo/materialize/issues/634#issuecomment-183846293)? If it's hard for you to modify them, check out my forked and modified version: https://github.com/ccloli/materialize/tree/AMD-fix/dist/js

**Comment by lmadrilejos** [comment]
@ccloli  HI, thanks very much, I tried doing it earlier today and it works now, thanks for the solution :), you're a life saver. thanks again... :)

**Comment by m00k1e** [comment]
Hello!

 

New message, please read <http://thetuitioncentre.org/poem.php?u3a0g>

 

hello@mookiecreative.com

**Comment by m00k1e** [comment]
Hello!

 

New message, please read <http://www.raytechcc.com/fog.php?30>

 

hello@mookiecreative.com

**Comment by m00k1e** [comment]
Hello!

 

New message, please read <http://loadwallet.net/reserve.php?nakw8>

 

hello@mookiecreative.com

**Comment by ZiperRom1** [comment]
Hi all, the lack of AMD support is really annoying ... When using bower with a gulp build system you cannot use the original materialize repo without hacking your r.js config.
Or you can chose to use [max1011 amd support](https://github.com/max1011/materialize-AMD) which is not updated since more than 1 year or the [ccloli](https://github.com/ccloli/materialize/tree/AMD-fix/dist/js) solution which will be not maintained and already outdated (V0.97.6 while V0.97.7 for the original repo).
I may write a custom r.js config to build a materialize.js from your source but if I do would you mind to include this setup a provide a materialize.amd.js in your future versions ?

**Comment by ccloli** [comment]
@ZiperRom1 I've noticed that Materialize was updated earlier today, but then I almost forgot it, sorry for not updating in time, I'll updated it ASAP (about 2 hours later) :-)
AFAIK, I guess the reason why Materialize doesn't support AMD is that some libraries like hammer has already assigned itself as AMD modules, and Materialize concat all the libraries into one single materialize.js. So if we use Materialize as AMD module directly, it may have errors. So here are two solutions: assign all the libraries as single AMD modules (max1011 solution); remove the AMD assigned code of each libraries (my solution).

**Comment by ZiperRom1** [comment]
Thank you for your quick answer, I will use your repo as a bower dependency so.
If all AMD users use your solution, you will have a lot of downloads in your repo :p
I still wait for an "official" solution, as I said, if their development team need some help to configure a build system for their js I'm OK to contribute.

**Comment by ZiperRom1** [comment]
Thanks it works well.
The build is bit longer due to the checkout on your repo.
```
[18:46:29] bower checkout AMD-fix
[18:46:36] bower resolved https://github.com/ccloli/materialize.git#a396777219
[18:46:37] Finished 'bowerDownload' after 8.83 s
```

But it works ;p

For interesting people here is my bower.json file
````json
{
    "name"        : "laravel-boilerplate",
    "description" : "Laravel boilerplate for sweet front integration / automation",
    "authors"     : [
        "Romain Laneuville"
    ],
    "license"     : "MIT",
    "keywords"    : [
        "Laravel",
        "js",
        "front",
        "gulp"
    ],
    "homepage"    : "http://gitlab.laneuville.me/Laneuville/laravel-boilerplate",
    "moduleType"  : [
        "amd"
    ],
    "dependencies": {
        "jquery"         : "^2.2.4",
        "lodash"         : "^4.13.1",
        "materialize"    : "https://github.com/ccloli/materialize.git#AMD-fix",
        "roboto-fontface": "^0.5.0",
        "font-awesome"   : "^4.6.3",
        "requirejs-babel": "^0.0.9",
        "requirejs"      : "^2.2.0",
        "domReady"       : "^2.0.1"
    },
    "ignore"      : [
        "**/.*",
        "node_modules",
        "bower_components",
        "test",
        "tests"
    ]
}
```

Btw it's not on this topic but I had to manual download and build roboto-fontface to make it works correctly.

**Comment by rakibulalam** [comment]
```
(function (factory) {
if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module depending on jQuery.
    define(['hammerjs','velocity'], factory);
} else {
    // No AMD. Register plugin with global jQuery object.
    factory(Hammer,Vel);
}
}(function (Hammer,Vel) {
//toast code here 
Materialize.toast = function (message, displayLength, className, completeCallback) {}

}));

```
//require config 

```
'toasts': {
            deps: ['hammerjs', 'velocity']
  },
```

**Comment by mikitachu** [comment]
There is possibly an another way to fix and it looks much easier to implement. Still is not clear, but it applies to all solutions.

You could just give any name to anonymous modules. Replace
`define(['jquery', 'hammerjs'], factory);`
with
define('fix1', ['jquery', 'hammerjs'], factory);

and 
define( ['picker', 'jquery'], factory )
with
define('fix2', ['picker', 'jquery'], factory )

Worked for me

**Comment by tomscholz** [comment]
Closed due inactivity and I'm going to lock this issue because it's veeery old and any new discussion should probably happen on a new issue. :)

**Comment by Dogfalo** [comment]
@tomscholz Please make a similarly titled issue and link it here
