### ISSUE TITLE
Sidebar Items Render Oddly

### ISSUE THREAD

**Issue by alanjames1987** [Dogfalo/materialize#687]
When certain items, like switches and badges, are put in the sidebar the placement and rendering of them is very odd. I can't describe this well so I have included a screenshot below.

![sidebar](https://cloud.githubusercontent.com/assets/765326/6201748/a0b66ff6-b489-11e4-9eaa-387aab9b5f2f.png)

I'm sure there are other items that render oddly but I have not tried all items in the sidebar.

**Comment by Dogfalo** [comment]
Switches have been fixed, see #683

**Comment by alanjames1987** [comment]
The screenshot above is from 45a809a96be690d402a285a3a080929c2c1f654a, the most recent commit and one commit after #683 got resolved. 

Here is the code I used to create it.

```html
<div class="navbar-fixed">
	<nav>

		<div class="nav-wrapper black">

			<i class="mdi-navigation-menu button-collapse" data-activates="nav-mobile"></i>

			<ul class="right">
				<li><a href="#">Navbar Link</a></li>
			</ul>

			<ul id="nav-mobile" class="side-nav">

				<li>
					<a href="#">Link in Sidebar</a>
				</li>

				<li>
					<a href="#!">Alan <span class="new badge">1</span></a>
				</li>

				<li>

					<div class="switch">
						<label>
							Off
							<input type="checkbox">
							<span class="lever"></span>
							On
						</label>
					</div>

				</li>

			</ul>

		</div>

	</nav>
</div>
```

**Comment by Dogfalo** [comment]
I just tested your code, the switch is working as intended

**Comment by alanjames1987** [comment]
I recloned the repo to my project and I am still getting the same thing. After I run `grunt sass:expanded` the switch is fixed, but not the badge.

Here is what I get now.

![sidebar](https://cloud.githubusercontent.com/assets/765326/6202135/6e46070a-b4a4-11e4-8c8c-e44e3e4354f2.jpeg)

**Comment by Dogfalo** [comment]
Badges in Collapsible request is already open here: #687

**Comment by alanjames1987** [comment]
#687 is THIS issue.

**Comment by Dogfalo** [comment]
I meant #581, sorry.

**Comment by alanjames1987** [comment]
Cool. I will follow that issue.

Thank you for your quick reply.
